kind: BuildConfig
apiVersion: v1
metadata:
  name: ncat-egress-router
spec:
  triggers:
    - type: GitHub
      github:
        secret: secret101
    - type: Generic
      generic:
        secret: secret101
    -type: ImageChange
  source:
    type: Git
    git:
      uri: https://github.com/nstrug/openshift_ncat_router.git
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: registry.access.redhat.com/rhel7:latest
  output:
    to: ImageStreamTag
    name: ncat-egress-router:latest
